### ISSUE TITLE
Bot not start

### ISSUE THREAD

**Issue by Jebati** [rodrikv/outline-manager#2]
```
outline-manager-bot-bot-1       | Traceback (most recent call last):
outline-manager-bot-bot-1       |   File "/usr/local/lib/python3.9/site-packages/outline_vpn/utils.py", line 14, in check_ssl_fingerprint
outline-manager-bot-bot-1       |     wrappedSocket.connect((address, port))
outline-manager-bot-bot-1       |   File "/usr/local/lib/python3.9/ssl.py", line 1376, in connect
outline-manager-bot-bot-1       |     self._real_connect(addr, False)
outline-manager-bot-bot-1       |   File "/usr/local/lib/python3.9/ssl.py", line 1363, in _real_connect
outline-manager-bot-bot-1       |     super().connect(addr)
outline-manager-bot-bot-1       | TypeError: str, bytes or bytearray expected, not NoneType
outline-manager-bot-bot-1       | 
outline-manager-bot-bot-1       | During handling of the above exception, another exception occurred:
outline-manager-bot-bot-1       | 
outline-manager-bot-bot-1       | Traceback (most recent call last):
outline-manager-bot-bot-1       |   File "/code/bot.py", line 201, in <module>
outline-manager-bot-bot-1       |     main()
outline-manager-bot-bot-1       |   File "/code/bot.py", line 173, in main
outline-manager-bot-bot-1       |     outline = OutlineVPN(os.environ["api_url"], cert_sha256=os.environ["certSha256"])
outline-manager-bot-bot-1       |   File "/usr/local/lib/python3.9/site-packages/outline_vpn/outline_vpn.py", line 36, in __init__
outline-manager-bot-bot-1       |     check_ssl_fingerprint(api_url, cert_sha256)
outline-manager-bot-bot-1       |   File "/usr/local/lib/python3.9/site-packages/outline_vpn/utils.py", line 16, in check_ssl_fingerprint
outline-manager-bot-bot-1       |     raise Exception(f"Connection Error: {e}")
outline-manager-bot-bot-1       | Exception: Connection Error: str, bytes or bytearray expected, not NoneType
```

.env
```
TOKEN=6514594456:ААFL9-Jt726р6НtFA7m7RAv6UkIJ1-UqvX6
api_url=32.253.185.218:63972/LncET74uGa1PrxDC74аzqg
certSha256=67ACC6016F823810E227A2E6FDFF14A206DA84C13A1FF81754FA5423CF8BD801
admins=["221273525"]
```

**Comment by rodrikv** [comment]
Add your protocol at the start of api_url.
example: http://32.253.185.218:63972/LncET74uGa1PrxDC74аzqg
